HairSalon/Models/ClassName.cs
namespace ProjectName.Models
{
  public class ClassName
  {

    // properties, methods, etc. will go here.

  }
}

HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    // properties
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Notes { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{

  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }

    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base (options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    // properties
    public int StylistId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Client> Clients { get; set; }

    // contructor
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }
  }
}

HairSalon/Controllers/ClassNameController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectName.Models;
using System.Collections.Generic;

namespace ProjectName.Controllers
{
  public class ClassNameController : Controller
  {
  }
}

HairSalon/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
  public class ClassNameController : Controller
  {
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;
    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Show()
    {
      return View();
    }

      public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Show");
    }
  }
}

HairSalon/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectName.Models;
using System.Collections.Generic;

namespace ProjectName.Controllers
{
  public class ClassNameController : Controller
  {
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

HairSalon/Controllers/StylistController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
  public class ClassNameController : Controller
  {
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Show(int id)
    {
        Stylist thisStylist = _db.Stylists.Include(stylists => stylists.Clients).FirstOrDefault(stylists => stylists.StylistId == id);
        return View(thisStylist);
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add New Client</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)<br>

    @Html.LabelFor(model => model.Notes)
    @Html.TextBoxFor(model => model.Notes)<br>

    @Html.LabelFor(model => model.StylistId)
    @Html.DropDownList("StylistId")
    <input type="submit" value="Add client"/>
}
<p>@Html.ActionLink("Show all Stylists", "Index", "Stylists")</p>

HairSalon/Views/Clients/Index.cshtml
<h4> Client successfully added!</h4>

<p>@Html.ActionLink("See all Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("Go back home", "Index", "Home")</p>

HairSalon/Views/Clients/Show.cshtml
@{
  Layout = "_Layout";
}

<h4> Client successfully added!</h4>

<p>@Html.ActionLink("See all Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("Go back home", "Index", "Home")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Salon Management System</h1>

<input type="button" value="See all stylists" onclick="location.href='@Url.Action("Index", "Stylists")'" />

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Salon Client Tracker</title>
    <link rel='stylesheet' href='~/../css/styles.css'>
  </head>
  <body>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new Stylist:</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    <input type="submit" value="Add new Stylist"/>
}
<p>@Html.ActionLink("Show all Stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist;

<h2>Are you sure you want to remove this stylist?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Remove" />
}

<p>@Html.ActionLink("See all Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("Go back home", "Index", "Home")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist;

<h2>Edit</h2>

<h4>Edit this Stylist's Name: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("See all Stylists", "Index")</p>
<p>@Html.ActionLink("Go back home", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

@if (@Model.Count == 0)
{
  <h3>No Stylists have been added yet!</h3>
} 

@foreach (Stylist stylist in Model)
{

  <h2>Here are all hair stylists currently employed at your salon:</h2>
  <p>Click a stylist's name to see a list of their clients.</p>
  <h4>@Html.ActionLink($"{stylist.Name}", "Show", new { id = stylist.StylistId })</h4>
}


<p>@Html.ActionLink("Add new Stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Show.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model HairSalon.Models.Stylist;

<h2> @Html.DisplayFor(model => model.Name)'s Clients</h2>

<ul>
@if (@Model.Clients.Count == 0)
{
  <p>This stylist has no clients yet!</p>
}

@foreach (Client client in Model.Clients)
{
  <p>Name: @client.Name</p>
  <p>Notes: @client.Notes</p>
}
</ul>

<p>@Html.ActionLink("Add Client", "Create", "Clients")</p>
<p>@Html.ActionLink("Remove this Stylist", "Delete", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Edit this Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("See all stylists", "Index")</p>